FROM node:19-alpine As development

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json tsconfig.json

RUN npm install

COPY apps/orders apps/orders

RUN npm run build orders

FROM node:alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json tsconfig.json

RUN npm install --only=production

COPY dist dist

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/apps/orders/main"]